"""Splice generated parts (src/<part>/out/sections.html + css.css) into the deck, after part 3.

Each part's build.py writes only its own out/ files; this script is the single writer of index.html for parts 4+.
Blocks are delimited by <!-- partN:begin --> / <!-- partN:end --> (and /* partN:begin */ ... in CSS), so reruns
replace only those blocks.

  python3 src/merge_parts.py                         # all parts -> index.html
  python3 src/merge_parts.py --only part5 --out /tmp/x.html   # preview one part in a copy
"""
import argparse, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
PARTS = ['part4a', 'part4b', 'part5a', 'part5b', 'part6a', 'part6b', 'part6c']          # deck order, all after part 3
ANCHOR_SEC = '  <!-- part3:end -->\n'
ANCHOR_CSS = '/* ---------- sidebar + controls ---------- */'

ap = argparse.ArgumentParser()
ap.add_argument('--out', default=str(ROOT / 'index.html'))
ap.add_argument('--only', nargs='*', default=None)
a = ap.parse_args()
deck = (ROOT / 'index.html').read_text()
use = [p for p in PARTS if a.only is None or p in a.only]
for p in PARTS:   # drop old blocks (all parts, so --only previews show just that part)
    deck = re.sub(rf'  <!-- {p}:begin.*?<!-- {p}:end -->\n', '', deck, flags=re.S)
    deck = re.sub(rf'/\* {p}:begin.*?/\* {p}:end \*/\n', '', deck, flags=re.S)
sec, css = '', ''
for p in use:
    d = ROOT / 'src' / p / 'out'
    if not (d / 'sections.html').exists(): continue
    sec += f'  <!-- {p}:begin (generated by src/{p}/build.py) -->\n' + (d / 'sections.html').read_text().rstrip('\n') + f'\n  <!-- {p}:end -->\n'
    if (d / 'css.css').exists():
        css += f'/* {p}:begin (generated by src/{p}/build.py) */\n' + (d / 'css.css').read_text().rstrip('\n') + f'\n/* {p}:end */\n'
assert ANCHOR_SEC in deck and ANCHOR_CSS in deck
deck = deck.replace(ANCHOR_SEC, ANCHOR_SEC + sec, 1).replace(ANCHOR_CSS, css + ANCHOR_CSS, 1)
pathlib.Path(a.out).write_text(deck)
print('wrote', a.out, 'parts:', [p for p in use if (ROOT / 'src' / p / 'out' / 'sections.html').exists()])
